# application properties
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always

discord:
  client_id:
  token:
  permissions: 1234

clients:
  retries: 3